### ISSUE TITLE
Pipeline training fails

### ISSUE THREAD

**Issue by joshhansen** [steveash/jg2p#2]
As per the README I'm attempting to train my own models, using `./mrun ./PipelineTrain.groovy`, but I get an error I can't seem to resolve. Basically it seems to fail at deserializing a pronouncer model located at ../resources/pipe_43sy_cmu7_fixsg_1.dat

This is no surprise as the file seems to have a text format, whereas the code is expecting binary readable by ObjectInputStream.

Here's the full error output:

$ ./mrun ./PipelineTrain.groovy 
Do you want to auto-delete the instance after finishing y/n? n
[INFO] Scanning for projects...
[INFO] 
[INFO] -----------------< com.github.steveash.jg2p:jg2p-core >-----------------
[INFO] Building jg2p-core 1.1.3-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.6.0:java (default-cli) @ jg2p-core ---
17:23:13,372 -- groovy.lang.GroovyShell.main()              psaurus - Starting training with cmu7b.train with opts TrainOptions{
	minXGram=1,
	maxXGram=4,
	minYGram=1,
	maxYGram=3,
	includeXEpsilons=true,
	includeEpsilonYs=false,
	onlyOneGrams=false,
	trainingAlignerMaximizer=JOINT,
	trainingAlignerMaxIterations=100,
	probDeltaConvergenceThreshold=1.0E-5,
	maxPronouncerTrainingIterations=400,
	trimFeaturesUnderPercentile=0,
	initCrfFromModelFile='../resources/pipe_43sy_cmu7_fixsg_1.dat',
	semiSupervisedFactor=0.6,
	useWindowWalker=true,
	windowPadding=0,
	topKAlignCandidates=1,
	minAlignScore=-2147483648,
	trainingFile=null,
	outputFile=null,
	format=TAB}
17:23:14,116 -- groovy.lang.GroovyShell.main() train.PipelineTrainer - Validating that all inputs are good before starting...
17:23:14,167 -- groovy.lang.GroovyShell.main()              psaurus - Problem trying to train model 
java.lang.IllegalStateException: Failed validating that all inputs can be read and parsed before wasting a lot of timetrying to do training; please correct init model files
	at com.github.steveash.jg2p.train.PipelineTrainer.validateInputs(PipelineTrainer.java:170)
	at com.github.steveash.jg2p.train.PipelineTrainer.train(PipelineTrainer.java:125)
	at com.github.steveash.jg2p.train.PipelineTrainer$train.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:110)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:138)
	at PipelineTrain.run(PipelineTrain.groovy:86)
	at groovy.lang.GroovyShell.runScriptOrMainOrTestOrRunnable(GroovyShell.java:261)
	at groovy.lang.GroovyShell.run(GroovyShell.java:522)
	at groovy.lang.GroovyShell.run(GroovyShell.java:511)
	at groovy.ui.GroovyMain.processOnce(GroovyMain.java:650)
	at groovy.ui.GroovyMain.run(GroovyMain.java:381)
	at groovy.ui.GroovyMain.process(GroovyMain.java:367)
	at groovy.ui.GroovyMain.processArgs(GroovyMain.java:126)
	at groovy.ui.GroovyMain.main(GroovyMain.java:106)
	at groovy.lang.GroovyShell.main(GroovyShell.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: java.io.StreamCorruptedException: invalid stream header: 76657273
	at com.google.common.base.Throwables.propagate(Throwables.java:160)
	at com.github.steveash.jg2p.util.ModelReadWrite.read(ModelReadWrite.java:101)
	at com.github.steveash.jg2p.util.ModelReadWrite.readPronouncerFrom(ModelReadWrite.java:106)
	at com.github.steveash.jg2p.train.PipelineTrainer.validateInputs(PipelineTrainer.java:149)
	... 21 more
Caused by: java.io.StreamCorruptedException: invalid stream header: 76657273
	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:865)
	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:357)
	at com.github.steveash.jg2p.util.ReadWrite.readFromSource(ReadWrite.java:46)
	at com.github.steveash.jg2p.util.ReadWrite.readFromFile(ReadWrite.java:42)
	at com.github.steveash.jg2p.util.ModelReadWrite.read(ModelReadWrite.java:99)
	... 23 more
17:23:14,179 -- groovy.lang.GroovyShell.main()              psaurus - Wrote to ../resources/pipe_43sy_cmu7_fixsg_3.dat
17:23:14,180 -- groovy.lang.GroovyShell.main()              psaurus - Entire training process took 817.6 ms
17:23:14,181 -- groovy.lang.GroovyShell.main()              psaurus - ***********************************Finished*************************************
17:23:14,181 -- groovy.lang.GroovyShell.main()              psaurus - testing right now...
Caught: java.lang.NullPointerException
java.lang.NullPointerException
	at com.github.steveash.jg2p.PipelineModel.makeSparse(PipelineModel.java:106)
	at com.github.steveash.jg2p.PipelineModel$makeSparse.call(Unknown Source)
	at PipelineTrain.run(PipelineTrain.groovy:100)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282)
Finished script execution

**Comment by steveash** [comment]
ah yes you need git-lfs installed in order to checkout and download the large files. Github has a limit of the filesize that you can store there (and generally git isn't meant for large files) so there is a separate things called git-lfs, which Github supports, that treat big blobs as separate things and stores them separately, grabbing them on-demand. See https://help.github.com/articles/versioning-large-files/ and the installation instructions: https://github.com/git-lfs/git-lfs/wiki/Installation 

After git-lfs is installed you can either re-clone or to just download the files and update your local cloned repo run `git lfs pull` now you should have binary files.

**Comment by steveash** [comment]
i'll update the readme

**Comment by joshhansen** [comment]
That's helpful information, thanks!
